version: "3.9"
services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=conversiondb
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_PASSWORD
      start_period: 40s
      interval: 5s
      timeout: 5s
      retries: 8
    networks:
      - inatel

  conversion-manager:

    build:
      dockerfile: ./Dockerfile
      context: ./
      args:
        JAR_FILE: target/conversion-manager-0.0.1-SNAPSHOT.jar
    image: conversion-manager
    container_name: conversion-manager
    ports:
      - 8080:8080
    environment:
      - MYSQL_CONTAINER=mysql
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    networks:
      - inatel

networks:
  inatel:
    driver: bridge
